{% set name = "conda-souschef" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/conda_souschef-{{ version }}.tar.gz
  sha256: 0df9fa12d826ab349e8006e498c6067b3a5161cf5b860baf08601829cb1b200b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=30.3.0
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - ruamel.yaml >=0.15.3
    - ruamel.yaml.jinja2

test:
  imports:
    - souschef
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marcelotrevisani/souschef
  summary: Project to handle conda recipes
  dev_url: https://github.com/marcelotrevisani/souschef
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
